### ISSUE TITLE
Can c++ and CUDA be split into their separate repos?

### ISSUE THREAD

**Issue by zenkavi** [aDDM-Toolbox/ADDM.cu#1]
I'm thinking through how to organize all the code for fitting the aDDM in one organization. Does the CUDA code depend on the rest of the C++ code? Can it be refactored into its own repo so we can have separate aDDM-CPP and aDDM-CUDA repos within the aDDM-Toolbox organization?

**Comment by jakegoldm** [comment]
The CUDA algorithm for computing trial likelihoods is separate from the CPU algorithm for computing trial likelihoods (so it's written twice in the codebase). I don't think it would be too difficult to create separate repositories with each of the components. There would be some repeated code in terms of the auxiliary features of the toolbox (simulations, function wrappers, etc..), but if that isn't a problem then it's certainly doable.

**Comment by zenkavi** [comment]
Great. I don't think some repeated code is too big of an issue. If there is a lot of it we can think about putting anything that would repeat into its own repo too and have it be a dependency.
